name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: npm
      - run: npm ci
      - run: npm run build

      - name: Zip package
        run: |
          mkdir -p /release
          zip -jr /release/send_vrc.zip ./dist/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "/release/send_vrc.zip"
          prerelease: ${{ contains(github.ref, '-beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
