name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: npm

      - name: Install Renovate CLI
      - run: npm install -g renovate

      - name: Validate renovate.json
        run: renovate-config-validator
